on: pull_request

jobs:
  lint:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 10m0s
          working-directory: .
          skip-pkg-cache: true
  test:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test