on:
    push:
      branches:
        - main
  
name: release-please
jobs:
    release-please:
      runs-on: ARM64
      steps:
        # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
        # For why we need to generate a token and not use the default
        - name: Generate token
          id: generate_token
          uses: tibdex/github-app-token@v2
          with:
            app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
            private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}
  
        - name: release please
          uses: google-github-actions/release-please-action@v4
          id: release
          with:
            release-type: simple
            token: ${{ steps.generate_token.outputs.token }}
            pull-request-title-pattern: "chore${scope}: release${component} ${version}"
            changelog-types: '[ { "type": "feat", "section": "Features", "hidden": false }, { "type": "fix", "section": "Bug fixes", "hidden": false }, { "type": "build", "section": "Dependencies", "hidden": false }, { "type": "chore", "section": "Miscellaneous", "hidden": false }, { "type": "ci", "section": "Continuous integration", "hidden": false }, { "type": "perf", "section": "Improvements", "hidden": false }, { "type": "refactor", "section": "Improvements", "hidden": false }, { "type": "style", "section": "Miscellaneous", "hidden": false }, { "type": "docs", "section": "Documentation", "hidden": false }]'

 